const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const NAME_REGEX = /^.+$/;

const DICTIONARY_NAME_REGEX = /^.{2,30}$/;
const DICTIONARY_DESCRIPTION_REGEX = /^.{0,30}$/;

const WORD_ENGLISH_REGEX = /^[a-z-]{1,30}$/;
const WORD_TRANSCRIPTION_REGEX = /^.{1,60}$/;
const WORD_RUSSIAN_REGEX = /^[а-я-]{1,30}$/;
const WORD_DESCRIPTION_REGEX = /^.{0,30}$/;

export const REGEXES = {
  EMAIL_REGEX,
  NAME_REGEX,
  DICTIONARY_NAME_REGEX,
  DICTIONARY_DESCRIPTION_REGEX,
  WORD_ENGLISH_REGEX,
  WORD_TRANSCRIPTION_REGEX,
  WORD_RUSSIAN_REGEX,
  WORD_DESCRIPTION_REGEX,
};
