const GLOBAL_PREFIX = "/api";
const STATISTICS_PREFIX = "/statistics";
const AUTH_PREFIX = "/auth";
const DICTIONARY_PREFIX = "/dictionary";
const WORD_PREFIX = "/word";
const USER_PREFIX = "/user";
const ADMIN_PREFIX = "/admin";
const USER_SETTINGS_PREFIX = "/user-settings";
const LESSON_PREFIX = "/lesson";
const TASK_PREFIX = "/task";

const STATISTICS_ROUTE = `${GLOBAL_PREFIX}${STATISTICS_PREFIX}`;

const AUTH_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}`;
const LOGIN_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}/login`;
const LOGOUT_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}/logout`;
const REGISTRATION_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}/registration`;
const REFREASH_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}/refresh`;

const DICTIONARY_ROUTE = `${GLOBAL_PREFIX}${DICTIONARY_PREFIX}`;
const DICTIONARY_USER_ROUTE = `${GLOBAL_PREFIX}${DICTIONARY_PREFIX}${USER_PREFIX}`;
const DICTIONARY_REVIEW_ROUTE = `${GLOBAL_PREFIX}${DICTIONARY_PREFIX}/review`;
const DICTIONARY_ADMIN_ROUTE = `${GLOBAL_PREFIX}${DICTIONARY_PREFIX}${ADMIN_PREFIX}`;

const WORD_ROUTE = `${GLOBAL_PREFIX}${WORD_PREFIX}`;

const USER_ROUTE = `${GLOBAL_PREFIX}${USER_PREFIX}`;
const PERSONAL_CABINET_ROUTE = `${GLOBAL_PREFIX}${USER_PREFIX}/personal-cabinet`;

const USER_SETTINGS_ROUTE = `${GLOBAL_PREFIX}${USER_SETTINGS_PREFIX}`;

const LESSON_ROUTE = `${GLOBAL_PREFIX}${LESSON_PREFIX}`;
const LESSON_ADMIN_ROUTE = `${GLOBAL_PREFIX}${LESSON_PREFIX}${ADMIN_PREFIX}`;

const TASK_ROUTE = `${GLOBAL_PREFIX}${TASK_PREFIX}`;

export const ROUTES = {
  TASK_ROUTE,
  STATISTICS_ROUTE,
  AUTH_ROUTE,
  LOGIN_ROUTE,
  LOGOUT_ROUTE,
  REGISTRATION_ROUTE,
  REFREASH_ROUTE,
  DICTIONARY_ROUTE,
  DICTIONARY_USER_ROUTE,
  WORD_ROUTE,
  USER_ROUTE,
  PERSONAL_CABINET_ROUTE,
  USER_SETTINGS_ROUTE,
  DICTIONARY_ADMIN_ROUTE,
  DICTIONARY_REVIEW_ROUTE,
  LESSON_ROUTE,
  LESSON_ADMIN_ROUTE,
};
