const GLOBAL_PREFIX = "/api";
const STATISTICS_PREFIX = "/statistics";
const AUTH_PREFIX = "/auth";
const DICTIONARY_PREFIX = "/dictionary";
const WORD_PREFIX = "/word";

const STATISTICS_ROUTE = `${GLOBAL_PREFIX}${STATISTICS_PREFIX}`;

const AUTH_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}`;
const LOGIN_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}/login`;
const LOGOUT_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}/logout`;
const REGISTRATION_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}/registration`;
const REFREASH_ROUTE = `${GLOBAL_PREFIX}${AUTH_PREFIX}/refresh`;

const DICTIONARY_ROUTE = `${GLOBAL_PREFIX}${DICTIONARY_PREFIX}`;
const DICTIONARY_USER_ROUTE = `${GLOBAL_PREFIX}${DICTIONARY_PREFIX}/user`;

const WORD_ROUTE = `${GLOBAL_PREFIX}${WORD_PREFIX}`;

export const ROUTES = {
  STATISTICS_ROUTE,
  AUTH_ROUTE,
  LOGIN_ROUTE,
  LOGOUT_ROUTE,
  REGISTRATION_ROUTE,
  REFREASH_ROUTE,
  DICTIONARY_ROUTE,
  DICTIONARY_USER_ROUTE,
  WORD_ROUTE,
};
